http:
    request:
        #从连接池中获取到连接的最长时间
        connectionRequestTimeout: 500
        #数据传输的最长时间
        connectTimeout: 2000
        #提交请求前测试连接是否可用
        socketTimeout: 10000
        #提交请求前测试连接是否可用
        staleConnectionCheckEnabled: true

    pool:
       #设置连接总数
       maxTotal: 200
       #设置每个地址的并发数
       defaultMaxPerRoute: 100